services:
  cheatsheet-generator:
    image: nikodoom/zmk-viewer:latest
    volumes:
      - ./config:/config
      - ./cheatsheets:/images
    command: sh -c "rm /images/*;
                    zmk-viewer generate cradio -f /config/*.keymap --single;"
